services:
  orderservice:
    build:
      context: .
      dockerfile: OrderService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    deploy:
      replicas: 2
    networks:
      - my_network

  test:
    build:
      context: .
      dockerfile: test/Dockerfile
    networks:
      - my_network

networks:
  my_network:
    driver: bridge